package in.co.infinity.game.winner.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Entity
@Getter
@Setter
@ToString
@Table(name = "lap_details_tbl")
public class LapDetailsTable implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "lap_id")
	private String lapId;

	@Column(name = "lap_race_id")
	private String raceId;

	@Column(name = "lap_participant_id")
	private String participantId;

	@Column(name = "lap_name")
	private String lapName;

	@Column(name = "lap_finish_time")
	private Double finishTime;

	// Getters and Setters (These will be generated by Lombok through @Getter and
	// @Setter annotations)

}
