package in.co.infinity.game.winner.entity;

import java.io.Serializable;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Entity
@Getter
@Setter
@ToString
@Table(name = "participant_tbl")
public class ParticipantDetailTable implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "prt_id")
    private String participantId;

    @Column(name = "prt_name")
    private String participantName;

    @Column(name = "prt_race_id")
    private String raceId;

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    RaceDetailTable raceDetailTable;
    
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    List<LapDetailsTable> lapDetailsTablesList;
    
    // Getters and Setters (These will be generated by Lombok through @Getter and @Setter annotations)

}

