package in.co.infinity.game.winner.domain;

import java.io.Serializable;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class PaticipantDetailVO implements Serializable{

	private static final long serialVersionUID = 1L;

	private String participantId;

	private String participantName;

	private String raceId;

	// Getters and Setters (These will be generated by Lombok through @Getter and
	// @Setter annotations)

}
